# -------------------------------------------------------------------------------
# Project: Stock Analysis (https://github.com/anshulsolanki/stock_analysis)
# Author:  Anshul Solanki
# License: MIT License
# 
# DISCLAIMER: 
# This software is for educational purposes only. It is not financial advice.
# Stock trading involves risks. The author is not responsible for any losses.
# -------------------------------------------------------------------------------

"""
Copyright (c) 2026 Anshul Solanki

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

"""
VCP Recommendation Performance Evaluator

This script backtests the forward-performance of stock recommendations generated by the VCP screener.

Backtest Constraints & Logic:
-----------------------------
- 60-Day Cooldown: Automatically drops redundant entries for a Ticker if they occur within 60 
  calendar days of the initial trade, to simulate realistic portfolio entries.
- 30-Day Sufficiency Guard: Skips processing recent recommendations that do not yet have 
  30 trading days of forward historical data available.
- Performance Horizons: Measures precise percentage gains across 1, 3, 5, 10, 15, and 30 trading days.
- Support Monitoring: Tracks Stop Loss breaches, Pivot level undercuts, and calculates the Maximum Drawdown.

Usage:
------
python evaluate_recommendations.py --csv-path path/to/consolidated_results.csv
"""

import argparse
import os
import pandas as pd
import numpy as np
from datetime import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, '..', '..', 'data'))
CACHE_DIR = os.path.join(DATA_DIR, 'data_cache')

def evaluate_performance():
    # --- 1. Argument Parsing ---
    parser = argparse.ArgumentParser(description="VCP Recommendation Performance Evaluator")
    parser.add_argument('--csv-path', type=str, required=True, help="Path to consolidated_results.csv")
    args = parser.parse_args()

    if not os.path.exists(args.csv_path):
        print(f"Error: File not found at {args.csv_path}")
        return

    df_recs = pd.read_csv(args.csv_path)
    if df_recs.empty:
        print("Error: The provided CSV file is empty.")
        return
        
    # --- 2. 60-Day Interval Pre-Filtering ---
    df_recs['ParsedDate'] = pd.to_datetime(df_recs['Date'])
    df_recs = df_recs.sort_values(by='ParsedDate')

    def _apply_cooldown(group, days=60):
        """Keep first entry, then only entries >N days after the last kept entry."""
        group = group.sort_values('ParsedDate')
        kept = [True]
        last_date = group['ParsedDate'].iloc[0]
        for date in group['ParsedDate'].iloc[1:]:
            if (date - last_date).days > days:
                kept.append(True)
                last_date = date
            else:
                kept.append(False)
        return group[kept]

    df_recs = df_recs.groupby('Ticker', group_keys=False).apply(_apply_cooldown)
    df_recs = df_recs.drop(columns=['ParsedDate'])

    print(f"Filtered down to {len(df_recs)} unique 60-day interval recommendations. Starting evaluation...")

    evaluated_rows = []

    # --- 3. Forward Performance Analysis ---
    for index, row in df_recs.iterrows():
        ticker = row['Ticker']
        rec_date_str = row['Date']
        rec_close = float(row['Close'])
        target_price = float(row['Target'])
        stop_loss = float(row['Stop_Loss'])
        pivot_price = float(row['Pivot'])

        cache_path = os.path.join(CACHE_DIR, f"{ticker}_1d.csv")
        if not os.path.exists(cache_path):
            print(f"Warning: Cache not found for {ticker}. Skipping.")
            continue

        df_hist = pd.read_csv(cache_path, index_col=0, parse_dates=True)
        rec_date = pd.to_datetime(rec_date_str)
        if df_hist.index.tz is not None:
            rec_date = rec_date.tz_localize(df_hist.index.tz)
        
        # Find exact or nearest trading day index
        trading_days = df_hist.index
        if rec_date not in trading_days:
            valid_dates = trading_days[trading_days >= rec_date]
            if len(valid_dates) == 0:
                continue
            rec_date = valid_dates[0]

        idx = df_hist.index.get_loc(rec_date)
        
        # Skip recommendation if we do not have at least 30 days of forward data
        if len(df_hist) - idx - 1 < 30:
            continue
            
        # Slice forward 30 trading days (excluding entry day itself)
        df_forward = df_hist.iloc[idx + 1 : idx + 31]

        # Entry price is next day's open (realistic: screener runs after market close)
        entry_price = float(df_forward['Open'].iloc[0])

        # Breakout gap: how much the stock gapped from rec-day close to actual entry
        gap_pct = round(((entry_price - rec_close) / rec_close) * 100, 2)

        # 1. Horizon Performance Calculations
        perf_map = {}
        for days in [1, 3, 5, 10, 15, 30]:
            if len(df_forward) >= days:
                fwd_close = float(df_forward['Close'].iloc[days - 1])
                perf_map[f'Perf_{days}d'] = round(((fwd_close - entry_price) / entry_price) * 100, 2)
            else:
                perf_map[f'Perf_{days}d'] = np.nan

        # 2. Intraday / Forward Monitoring (Highs and Lows)
        forward_lows = df_forward['Low'].values
        forward_highs = df_forward['High'].values

        stop_loss_hit = any(forward_lows < stop_loss)
        target_hit = any(forward_highs >= target_price)
        price_below_pivot = any(forward_lows < pivot_price)

        lowest_below_pivot = np.nan
        if price_below_pivot:
            below_pivot_lows = forward_lows[forward_lows < pivot_price]
            lowest_below_pivot = round(float(np.min(below_pivot_lows)), 2)

        # 3. Trade Result (Which was hit first?)
        trade_result = 'Open'
        for l, h in zip(forward_lows, forward_highs):
            if l < stop_loss:
                trade_result = 'Loss'
                break
            if h >= target_price:
                trade_result = 'Win'
                break

        # 4. Max Drawdown
        min_low = np.min(forward_lows)
        max_drawdown = round(((min_low - entry_price) / entry_price) * 100, 2)

        row_ext = row.to_dict()
        row_ext.update({
            'Entry_Price': entry_price,
            'Gap_Pct': gap_pct,
            'Perf_1d': perf_map['Perf_1d'],
            'Perf_3d': perf_map['Perf_3d'],
            'Perf_5d': perf_map['Perf_5d'],
            'Perf_10d': perf_map['Perf_10d'],
            'Perf_15d': perf_map['Perf_15d'],
            'Perf_30d': perf_map['Perf_30d'],
            'Stop_Loss_Hit': stop_loss_hit,
            'Price_Below_Pivot': price_below_pivot,
            'Lowest_Price_Below_Pivot': lowest_below_pivot,
            'Trade_Result': trade_result,
            'Max_Drawdown_30d': max_drawdown
        })
        evaluated_rows.append(row_ext)

    df_evaluated = pd.DataFrame(evaluated_rows)
    
    output_path = os.path.join(os.path.dirname(args.csv_path), "performance_evaluated_results.csv")
    df_evaluated.to_csv(output_path, index=False)
    print(f"\n[SUCCESS] Evaluated results saved to: {output_path}")

    # --- 4. Statistical Summary ---
    perf_30d_valid = df_evaluated['Perf_30d'].dropna()
    valid_results = df_evaluated[df_evaluated['Trade_Result'].isin(['Win', 'Loss'])]

    print("\n" + "=" * 50)
    print("  Performance Evaluation Summary")
    print("=" * 50)

    if not valid_results.empty:
        total = len(valid_results)
        wins = len(valid_results[valid_results['Trade_Result'] == 'Win'])
        losses = len(valid_results[valid_results['Trade_Result'] == 'Loss'])
        win_rate = (wins / total) * 100
        loss_rate = (losses / total) * 100

        # Average win / loss percentages (using 30-day returns)
        win_returns = valid_results.loc[valid_results['Trade_Result'] == 'Win', 'Perf_30d'].dropna()
        loss_returns = valid_results.loc[valid_results['Trade_Result'] == 'Loss', 'Perf_30d'].dropna()
        avg_win = float(np.mean(win_returns)) if not win_returns.empty else 0
        avg_loss = float(np.mean(loss_returns)) if not loss_returns.empty else 0

        # Profit Factor: gross wins / abs(gross losses)
        gross_wins = float(win_returns.sum()) if not win_returns.empty else 0
        gross_losses = float(loss_returns.sum()) if not loss_returns.empty else 0
        profit_factor = abs(gross_wins / gross_losses) if gross_losses != 0 else np.inf

        # Expectancy: (win_rate × avg_win) + (loss_rate × avg_loss)
        expectancy = (win_rate / 100 * avg_win) + (loss_rate / 100 * avg_loss)

        # Max consecutive losses
        results_seq = valid_results['Trade_Result'].values
        max_consec_losses = 0
        current_streak = 0
        for r in results_seq:
            if r == 'Loss':
                current_streak += 1
                max_consec_losses = max(max_consec_losses, current_streak)
            else:
                current_streak = 0

        print(f"  Total Closed Trades : {total}")
        print(f"  Wins / Losses       : {wins} / {losses}")
        print(f"  Win Rate            : {win_rate:.2f}%")
        print("-" * 50)
        print(f"  Avg Win (30d)       : {avg_win:+.2f}%")
        print(f"  Avg Loss (30d)      : {avg_loss:+.2f}%")
        print(f"  Profit Factor       : {profit_factor:.2f}")
        print(f"  Expectancy / Trade  : {expectancy:+.2f}%")
        print("-" * 50)
        print(f"  Max Consec. Losses  : {max_consec_losses}")

    if not perf_30d_valid.empty:
        print("-" * 50)
        print(f"  Avg 30-day Return   : {np.mean(perf_30d_valid):+.2f}%")
        print(f"  Median 30-day Return: {np.median(perf_30d_valid):+.2f}%")

    # Breakout gap statistics
    if 'Gap_Pct' in df_evaluated.columns:
        gap_data = df_evaluated['Gap_Pct'].dropna()
        if not gap_data.empty:
            print("-" * 50)
            print(f"  Avg Breakout Gap    : {np.mean(gap_data):+.2f}%")
            print(f"  Median Breakout Gap : {np.median(gap_data):+.2f}%")

    open_trades = len(df_evaluated[df_evaluated['Trade_Result'] == 'Open'])
    if open_trades > 0:
        print("-" * 50)
        print(f"  Open Trades (no hit): {open_trades}")

    print("=" * 50 + "\n")

if __name__ == "__main__":
    evaluate_performance()
